[package]
name = "mrpack_downloader"
version = "1.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["cargo"] }
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
